apiVersion: v1
kind: ConfigMap
metadata:
  namespace: skywalking
  name: skywalking-config
  labels:
    app: skywalking
data:
  # #存储方式
  SW_ENABLE_UPDATE_UI_TEMPLATE: "true" # 开启dashboard编辑修改功能
  SW_STORAGE: "elasticsearch"
  SW_STORAGE_ES_CLUSTER_NODES: "es7-cluster.elasticsearch.svc.cluster.local:19200"
  SW_ES_USER: ""
  SW_ES_PASSWORD: ""
  #skywalking-oap监听端口
  SW_OAP_ADDRESS: "http://skywalking-oap.skywalking.svc.cluster.local:12800"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: skywalking-oap
  namespace: skywalking
  labels:
    app: skywalking-oap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: skywalking-oap
  template:
    metadata:
      labels:
        app: skywalking-oap
    spec:
      containers:
        - name: skywalking-oap
          image: apache/skywalking-oap-server:9.5.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 11800
              name: grpc
            - containerPort: 12800
              name: rest
          env:
            - name: SW_STORAGE #存储方式
              valueFrom:
                configMapKeyRef:
                  key: SW_STORAGE
                  name: skywalking-config

            - name: SW_STORAGE_ES_CLUSTER_NODES # es地址
              valueFrom:
                configMapKeyRef:
                  key: SW_STORAGE_ES_CLUSTER_NODES
                  name: skywalking-config

            - name: SW_ES_USER
              valueFrom:
                configMapKeyRef:
                  key: SW_ES_USER
                  name: skywalking-config

            - name: SW_ES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: SW_ES_PASSWORD
                  name: skywalking-config

            - name: TZ
              value: Asia/Shanghai
            - name: TIME_ZONE
              value: Asia/Shanghai
          resources:
            limits:
              cpu: '2'
              memory: 4Gi
            requests:
              cpu: '1'
              memory: 2Gi

          volumeMounts:
            - mountPath: /etc/localtime
              name: localtime
      volumes:
        - name: localtime
          hostPath:
            path: /etc/localtime

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: skywalking-ui
  namespace: skywalking
  labels:
    app: skywalking-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: skywalking-ui
  template:
    metadata:
      labels:
        app: skywalking-ui
    spec:
      containers:
        - name: skywalking-ui
          image: apache/skywalking-ui:9.5.0
          ports:
            - containerPort: 8080
              name: web
          env:
            - name: SW_OAP_ADDRESS
              valueFrom:
                configMapKeyRef:
                  key: SW_OAP_ADDRESS
                  name: skywalking-config

            - name: TZ
              value: Asia/Shanghai
            - name: TIME_ZONE
              value: Asia/Shanghai
          resources:
            limits:
              cpu: '1'
              memory: 2Gi
            requests:
              cpu: '1'
              memory: 1Gi

          volumeMounts:
            - mountPath: /etc/localtime
              name: localtime
      volumes:
        - name: localtime
          hostPath:
            path: /etc/localtime
